Repository hack-brooklyn/hack-brooklyn-plaza, pull requests merged in 2021-04, with the labels that each got.

#89 PLAZA-59 Edit announcement view
  backend/src/main/java/org/hackbrooklyn/plaza/controller/AnnouncementsController.java
  backend/src/main/java/org/hackbrooklyn/plaza/controller/RestControllerExceptionHandler.java
  backend/src/main/java/org/hackbrooklyn/plaza/exception/AnnouncementNotFoundException.java
  backend/src/main/java/org/hackbrooklyn/plaza/model/Announcement.java
  backend/src/main/java/org/hackbrooklyn/plaza/service/AnnouncementService.java
  backend/src/main/java/org/hackbrooklyn/plaza/service/impl/AnnouncementServiceImpl.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Routes.tsx
  frontend/src/components/announcements/Announcement.tsx
  frontend/src/components/announcements/AnnouncementBrowser.tsx
  frontend/src/components/announcements/AnnouncementEditor.tsx
  frontend/src/components/announcements/index.ts
  frontend/src/components/index.ts
  frontend/src/types.ts
  frontend/src/views/announcements/AnnouncementView/AnnouncementView.tsx
  frontend/src/views/announcements/AnnouncementView/index.ts
  frontend/src/views/announcements/EditAnnouncement/EditAnnouncement.tsx
  frontend/src/views/announcements/EditAnnouncement/index.ts
  frontend/src/views/announcements/PostAnnouncement/PostAnnoucement.tsx
  frontend/src/views/announcements/PostAnnouncement/index.ts
  frontend/src/views/announcements/index.ts
  frontend/src/views/root/Dashboard/Dashboard.tsx
Labels: feature

#94 PLAZA-109 Add team formation heading auto refresh
  frontend/src/actions/teamFormation.ts
  frontend/src/components/teamformation/ParticipantInboxModal.tsx
  frontend/src/components/teamformation/TeamFormationHeadingSection.tsx
  frontend/src/constants.ts
  frontend/src/reducers/index.ts
  frontend/src/reducers/teamFormation.ts
  frontend/src/types.ts
  frontend/src/util/teamFormation.ts
  frontend/src/views/teamformation/TeamFormationParticipantSetup/TeamFormationParticipantSetup.tsx
  frontend/src/views/teamformation/TeamFormationTeamSetup/TeamFormationTeamSetup.tsx
Labels: enhancement

#95 PLAZA-100 Add team formation participant profile editor modal
  frontend/src/assets/icons/profile-card.svg
  frontend/src/common/styles/teamformation/teamFormationInboxModalStyles.ts
  frontend/src/common/styles/teamformation/teamFormationModalStyles.ts
  frontend/src/components/MultiSelect.tsx
  frontend/src/components/teamformation/EditParticipantProfileModal.tsx
  frontend/src/components/teamformation/TeamFormationFormFields.tsx
  frontend/src/components/teamformation/TeamFormationHeadingSection.tsx
  frontend/src/components/teamformation/TopicsAndSkillsSelect.tsx
  frontend/src/components/teamformation/index.ts
  frontend/src/types.ts
  frontend/src/util/teamFormation.ts
  frontend/src/views/teamformation/TeamFormationParticipantSearch/TeamFormationParticipantSearch.tsx
  frontend/src/views/teamformation/TeamFormationParticipantSetup/components/ParticipantStepOne.tsx
  frontend/src/views/teamformation/TeamFormationParticipantSetup/components/ParticipantStepTwo.tsx
  frontend/src/views/teamformation/TeamFormationTeamSetup/TeamFormationTeamSetup.tsx
  frontend/src/views/teamformation/TeamFormationTeamSetup/components/TeamSetupComplete.tsx
  frontend/src/views/teamformation/TeamFormationTeamSetup/components/TeamStepOne.tsx
  frontend/src/views/teamformation/TeamFormationTeamSetup/components/TeamStepThree.tsx
  frontend/src/views/teamformation/TeamFormationTeamSetup/components/TeamStepTwo.tsx
Labels: feature

#96 PLAZA-110 Add team formation participant editor backend endpoints
  backend/src/main/java/org/hackbrooklyn/plaza/controller/TeamFormationController.java
  backend/src/main/java/org/hackbrooklyn/plaza/dto/CreateTeamFormationParticipantAndTeamDTO.java
  backend/src/main/java/org/hackbrooklyn/plaza/dto/CreateTeamFormationTeamDTO.java
  backend/src/main/java/org/hackbrooklyn/plaza/dto/TeamFormationParticipantFormDataDTO.java
  backend/src/main/java/org/hackbrooklyn/plaza/dto/TeamFormationParticipantFormDataWithBrowserVisibilityDTO.java
  backend/src/main/java/org/hackbrooklyn/plaza/service/TeamFormationService.java
  backend/src/main/java/org/hackbrooklyn/plaza/service/impl/TeamFormationServiceImpl.java
Labels: feature

#92 PLAZA-108 Event Backend
  backend/src/main/java/org/hackbrooklyn/plaza/controller/EventsController.java
  backend/src/main/java/org/hackbrooklyn/plaza/controller/RestControllerExceptionHandler.java
  backend/src/main/java/org/hackbrooklyn/plaza/dto/SaveEventDTO.java
  backend/src/main/java/org/hackbrooklyn/plaza/exception/EventNotFoundException.java
  backend/src/main/java/org/hackbrooklyn/plaza/model/Event.java
  backend/src/main/java/org/hackbrooklyn/plaza/repository/EventRepository.java
  backend/src/main/java/org/hackbrooklyn/plaza/service/EventService.java
  backend/src/main/java/org/hackbrooklyn/plaza/service/impl/EventServiceImpl.java
Labels: feature

#99 PLAZA-114 Add team formation backend endpoints for managing team formation teams
  backend/src/main/java/org/hackbrooklyn/plaza/controller/RestControllerExceptionHandler.java
  backend/src/main/java/org/hackbrooklyn/plaza/controller/TeamFormationController.java
  backend/src/main/java/org/hackbrooklyn/plaza/dto/CreateTeamFormationParticipantAndTeamDTO.java
  backend/src/main/java/org/hackbrooklyn/plaza/dto/TeamFormationParticipantFormDataDTO.java
  backend/src/main/java/org/hackbrooklyn/plaza/dto/TeamFormationParticipantFormDataWithBrowserVisibilityDTO.java
  backend/src/main/java/org/hackbrooklyn/plaza/dto/TeamFormationTeamFormDataDTO.java
  backend/src/main/java/org/hackbrooklyn/plaza/dto/TeamFormationTeamFormDataWithBrowserVisibilityDTO.java
  backend/src/main/java/org/hackbrooklyn/plaza/exception/TeamFormationNoPermissionException.java
  backend/src/main/java/org/hackbrooklyn/plaza/exception/TeamFormationTeamJoinRequestInaccessibleException.java
  backend/src/main/java/org/hackbrooklyn/plaza/model/TeamFormationParticipant.java
  backend/src/main/java/org/hackbrooklyn/plaza/model/TeamFormationTeam.java
  backend/src/main/java/org/hackbrooklyn/plaza/service/TeamFormationService.java
  backend/src/main/java/org/hackbrooklyn/plaza/service/impl/TeamFormationServiceImpl.java
Labels: feature

#100 PLAZA-115 Add team member contact info modal to team formation teams
  backend/src/main/java/org/hackbrooklyn/plaza/dto/TeamFormationParticipantFormDataDTO.java
  backend/src/main/java/org/hackbrooklyn/plaza/dto/TeamFormationParticipantFormDataWithBrowserVisibilityDTO.java
  backend/src/main/java/org/hackbrooklyn/plaza/model/TeamFormationParticipant.java
  backend/src/main/java/org/hackbrooklyn/plaza/service/impl/TeamFormationServiceImpl.java
  frontend/src/components/teamformation/EditParticipantProfileModal.tsx
  frontend/src/components/teamformation/EditTeamProfileModal.tsx
  frontend/src/components/teamformation/JoinedTeamMember.tsx
  frontend/src/components/teamformation/TeamContactModal.tsx
  frontend/src/components/teamformation/TeamFormationFormFields.tsx
  frontend/src/components/teamformation/TeamFormationHeadingSection.tsx
  frontend/src/components/teamformation/index.ts
  frontend/src/types.ts
  frontend/src/views/teamformation/TeamFormationParticipantSetup/TeamFormationParticipantSetup.tsx
  frontend/src/views/teamformation/TeamFormationParticipantSetup/components/ParticipantStepTwo.tsx
  frontend/src/views/teamformation/TeamFormationTeamSetup/TeamFormationTeamSetup.tsx
  frontend/src/views/teamformation/TeamFormationTeamSetup/components/TeamStepTwo.tsx
Labels: feature

#102 PLAZA-116 Add real-time browser push notifications
  .github/workflows/maven.yml
  backend/pom.xml
  backend/src/main/java/org/hackbrooklyn/plaza/ApplicationContext.java
  backend/src/main/java/org/hackbrooklyn/plaza/PlazaApplication.java
  backend/src/main/java/org/hackbrooklyn/plaza/controller/PushNotificationController.java
  backend/src/main/java/org/hackbrooklyn/plaza/controller/RestControllerExceptionHandler.java
  backend/src/main/java/org/hackbrooklyn/plaza/dto/NotificationContentDTO.java
  backend/src/main/java/org/hackbrooklyn/plaza/dto/SubscribeToPushNotificationDTO.java
  backend/src/main/java/org/hackbrooklyn/plaza/exception/ClientAlreadySubscribedException.java
  backend/src/main/java/org/hackbrooklyn/plaza/model/PushNotificationSubscription.java
  backend/src/main/java/org/hackbrooklyn/plaza/repository/PushNotificationSubscriptionRepository.java
  backend/src/main/java/org/hackbrooklyn/plaza/service/PushNotificationService.java
  backend/src/main/java/org/hackbrooklyn/plaza/service/impl/PushNotificationServiceImpl.java
  backend/src/main/java/org/hackbrooklyn/plaza/util/PushNotificationUtils.java
  backend/src/main/resources/application-test.properties
  backend/src/test/java/org/hackbrooklyn/plaza/PlazaApplicationTests.java
  backend/src/test/java/org/hackbrooklyn/plaza/controller/ApplyTests.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/src/service-worker.ts
  frontend/src/serviceWorkerRegistration.ts
  frontend/src/util/notificationService.ts
Labels: feature

#103 PLAZA-117 Add push notifications for announcements
  backend/src/main/java/org/hackbrooklyn/plaza/service/impl/AnnouncementServiceImpl.java
Labels: feature

#105 PLAZA-118 Add expanded push notification options
  backend/src/main/java/org/hackbrooklyn/plaza/dto/NotificationContentDTO.java
  backend/src/main/java/org/hackbrooklyn/plaza/service/impl/AnnouncementServiceImpl.java
  backend/src/main/java/org/hackbrooklyn/plaza/util/PushNotificationUtils.java
  frontend/src/service-worker.ts
Labels: enhancement

#106 PLAZA-119 Add push notifications for team formation
  backend/src/main/java/org/hackbrooklyn/plaza/service/impl/TeamFormationServiceImpl.java
Labels: feature

#107 PLAZA-120 Add announcement posting on Discord
  .github/workflows/maven.yml
  backend/pom.xml
  backend/src/main/java/org/hackbrooklyn/plaza/service/impl/AnnouncementServiceImpl.java
Labels: feature

#108 Hack Brooklyn Plaza 0.4.0
  .github/workflows/maven.yml
  backend/pom.xml
  backend/src/main/java/org/hackbrooklyn/plaza/ApplicationContext.java
  backend/src/main/java/org/hackbrooklyn/plaza/PlazaApplication.java
  backend/src/main/java/org/hackbrooklyn/plaza/controller/PushNotificationController.java
  backend/src/main/java/org/hackbrooklyn/plaza/controller/RestControllerExceptionHandler.java
  backend/src/main/java/org/hackbrooklyn/plaza/dto/NotificationContentDTO.java
  backend/src/main/java/org/hackbrooklyn/plaza/dto/SubscribeToPushNotificationDTO.java
  backend/src/main/java/org/hackbrooklyn/plaza/exception/ClientAlreadySubscribedException.java
  backend/src/main/java/org/hackbrooklyn/plaza/model/PushNotificationSubscription.java
  backend/src/main/java/org/hackbrooklyn/plaza/repository/PushNotificationSubscriptionRepository.java
  backend/src/main/java/org/hackbrooklyn/plaza/security/SecurityConfig.java
  backend/src/main/java/org/hackbrooklyn/plaza/service/PushNotificationService.java
  backend/src/main/java/org/hackbrooklyn/plaza/service/impl/AnnouncementServiceImpl.java
  backend/src/main/java/org/hackbrooklyn/plaza/service/impl/PushNotificationServiceImpl.java
  backend/src/main/java/org/hackbrooklyn/plaza/service/impl/TeamFormationServiceImpl.java
  backend/src/main/java/org/hackbrooklyn/plaza/util/PushNotificationUtils.java
  backend/src/main/resources/application-test.properties
  backend/src/test/java/org/hackbrooklyn/plaza/PlazaApplicationTests.java
  backend/src/test/java/org/hackbrooklyn/plaza/controller/ApplyTests.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Navbar.tsx
  frontend/src/components/teamformation/TeamFormationHeadingSection.tsx
  frontend/src/index.tsx
  frontend/src/service-worker.ts
  frontend/src/serviceWorkerRegistration.ts
  frontend/src/util/notificationService.ts
  frontend/src/views/root/Landing/Landing.tsx
Labels: release

#109 Hack Brooklyn Plaza 0.4.1
  backend/src/main/java/org/hackbrooklyn/plaza/model/Event.java
  frontend/src/App.tsx
  frontend/src/views/teamformation/TeamFormationParticipantSearch/TeamFormationParticipantSearch.tsx
  frontend/src/views/teamformation/TeamFormationTeamSearch/TeamFormationTeamSearch.tsx
Labels: release

#110 PLAZA-22 Add live hackathon dashboard
  frontend/example.env
  frontend/src/assets/icons/devpost.svg
  frontend/src/assets/icons/discord.svg
  frontend/src/common/styles/root/dashboardStyles.ts
  frontend/src/components/announcements/Announcement.tsx
  frontend/src/components/announcements/AnnouncementBrowser.tsx
  frontend/src/components/announcements/AnnouncementEditor.tsx
  frontend/src/index.tsx
  frontend/src/types.ts
  frontend/src/views/announcements/EditAnnouncement/EditAnnouncement.tsx
  frontend/src/views/announcements/PostAnnouncement/PostAnnoucement.tsx
  frontend/src/views/root/Dashboard/Dashboard.tsx
  frontend/src/views/root/Dashboard/components/ChecklistSection.tsx
  frontend/src/views/root/Dashboard/components/Live/AnnouncementsSection.tsx
  frontend/src/views/root/Dashboard/components/Live/Live.tsx
  frontend/src/views/root/Dashboard/components/Live/ScheduleSection.tsx
  frontend/src/views/root/Dashboard/components/Live/TimeRemainingSection.tsx
  frontend/src/views/root/Dashboard/components/Live/index.ts
  frontend/src/views/root/Dashboard/components/PreEvent/ApplicationStatusSection.tsx
  frontend/src/views/root/Dashboard/components/PreEvent/ChecklistSection.tsx
  frontend/src/views/root/Dashboard/components/PreEvent/CountdownSection.tsx
  frontend/src/views/root/Dashboard/components/PreEvent/PreEvent.tsx
  frontend/src/views/root/Dashboard/components/PreEvent/index.ts
  frontend/src/views/root/Dashboard/components/index.ts
Labels: feature

#111 PLAZA-121 Add event reminder push notifications
  backend/src/main/java/org/hackbrooklyn/plaza/service/impl/EventServiceImpl.java
  backend/src/main/java/org/hackbrooklyn/plaza/service/impl/PushNotificationServiceImpl.java
  backend/src/main/java/org/hackbrooklyn/plaza/util/SendEventPushNotificationsTask.java
Labels: feature

#112 PLAZA-111 Schedule builder view
  backend/src/main/java/org/hackbrooklyn/plaza/controller/EventsController.java
  backend/src/main/java/org/hackbrooklyn/plaza/dto/SaveEventDTO.java
  backend/src/main/java/org/hackbrooklyn/plaza/model/Event.java
  backend/src/main/java/org/hackbrooklyn/plaza/model/SavedEvent.java
  backend/src/main/java/org/hackbrooklyn/plaza/repository/SavedEventRepository.java
  backend/src/main/java/org/hackbrooklyn/plaza/service/EventService.java
  backend/src/main/java/org/hackbrooklyn/plaza/service/impl/EventServiceImpl.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Routes.tsx
  frontend/src/assets/icons/red-circle.svg
  frontend/src/assets/icons/white-star.svg
  frontend/src/assets/icons/yellow-star.svg
  frontend/src/components/Navbar.tsx
  frontend/src/components/announcements/Announcement.tsx
  frontend/src/components/schedulebuilder/Event.tsx
  frontend/src/components/schedulebuilder/EventDetail.tsx
  frontend/src/components/schedulebuilder/EventDetailModal.tsx
  frontend/src/components/schedulebuilder/EventEditor.tsx
  frontend/src/components/schedulebuilder/ScheduleViewer.tsx
  frontend/src/components/schedulebuilder/index.ts
  frontend/src/index.tsx
  frontend/src/security/accessControl.ts
  frontend/src/types.ts
  frontend/src/views/schedulebuilder/CreateEvent/CreateEvent.tsx
  frontend/src/views/schedulebuilder/CreateEvent/index.ts
  frontend/src/views/schedulebuilder/EditEvent/EditEvent.tsx
  frontend/src/views/schedulebuilder/EditEvent/index.ts
  frontend/src/views/schedulebuilder/ScheduleBuilder/ScheduleBuilder.tsx
  frontend/src/views/schedulebuilder/ScheduleBuilder/index.ts
  frontend/src/views/schedulebuilder/index.ts
Labels: feature

#114 Hack Brooklyn Plaza 1.0.1
  backend/pom.xml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Routes.tsx
  frontend/src/views/schedule/ScheduleBuilder/ScheduleBuilder.tsx
Labels: release
